[tool.poetry]
name = "cluedin"
version = "0.1.1"
description = ""
authors = ["Roman Klimenko <romaklimenko@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.29.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
